# Generated by Django 4.2.9 on 2026-03-06 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("question", models.TextField()),
                ("intent", models.JSONField()),
                ("entity", models.CharField(db_index=True, max_length=100)),
                ("intent_type", models.CharField(db_index=True, max_length=50)),
                ("executed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("execution_time_ms", models.IntegerField()),
                ("result_count", models.IntegerField(null=True)),
                ("response", models.TextField(blank=True)),
                ("interface", models.CharField(db_index=True, max_length=50)),
                ("success", models.BooleanField(db_index=True, default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("cache_hit", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-executed_at"],
                        name="core_queryl_user_id_f3cba4_idx",
                    ),
                    models.Index(
                        fields=["entity", "-executed_at"],
                        name="core_queryl_entity_8c59e1_idx",
                    ),
                ],
            },
        ),
    ]
