# Generated by Django 4.2.9 on 2026-03-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="input_tokens",
            field=models.IntegerField(
                blank=True, help_text="Number of input tokens used", null=True
            ),
        ),
        migrations.AddField(
            model_name="querylog",
            name="output_tokens",
            field=models.IntegerField(
                blank=True, help_text="Number of output tokens used", null=True
            ),
        ),
        migrations.AddField(
            model_name="querylog",
            name="total_tokens",
            field=models.IntegerField(
                blank=True, help_text="Total tokens (input + output)", null=True
            ),
        ),
    ]
