# Generated by Django 4.2.9 on 2026-03-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_querylog_input_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="estimated_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Estimated cost in USD based on token usage and model pricing",
                max_digits=10,
                null=True,
            ),
        ),
    ]
